
@url = http://localhost:81 
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJUZWFjaGVyMUBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjY5NTQxYWNkLWUzMGYtNDZmYS05OGJkLTFhNTc5Yzk5NjRhMSIsImV4cCI6MTcxNDc2NzMxNiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo0OTAwIiwiYXVkIjoiQVBJIn0.4A0zaFwze3P8Dxc8kZAJDv69U0Xl7MkrSwxAiECso64
@jwtiis = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJvbmVibGFjazM0MkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE2OGVkNDZjLTM2MDItNGIwOC04ZTdjLTg1MDEyZTI4MzYwNCIsImV4cCI6MTcxNTU1ODk3NiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo0OTAwIiwiYXVkIjoiQVBJIn0.1mKdlX6iETH9qva8xZopHhZkvq-wqfep0KQZNdSPNnM

# For more info on HTTP files go to https://aka.ms/vs/httpfile
GET {{url}}/api/Global/GetGroup
Content-Type: application/json
Authorization: Bearer {{jwtiis}}

###
POST  {{url}}/api/Auth/login
Content-Type: application/json

{
  "email": "oneblack342@gmail.com ",
  "Password":"Candidate1@123"
}

###
POST {{url}}/odata/Langua/Session/Update?Id=1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{ 
  "Name" : "Test",
  "GroupId" : 1,
  "TeacheriD":1,
  Start : DateTime.Now,
  End : DateTime.Now
}

###
GET {{url}}/odata/Langua/Sessions?$filter name eq 'Francais'
#filter=name eq 'ddd'
# GET {{url}}/odata/Langua/Sessions?$filter=name eq 'Anglais'

###
POST https://localhost:44395/odata/Langua/Sessions
Content-Type: application/json
Set-Cookie: AspNetCore.Identity.Application=CfDJ8CVQ8jxYvb5KksJ5MPXMnqTXM7B4GgdJoV-3GCbaZR4UHQkfLT8ZUCrWQE47sqWnvKPYtTqnO_2b0QuBps4ZIRQhAECBlRTrONU4y6Xq41rM6wv2EeBcuLtfVp2DvIrTgUiNlw3KOGNTxbluBVS0xmf-mGH1Z-kmFfhLgDE_15xgFLo5vVmUU8HJC_mua9TBBB8n71uxvGSON7bw-oI4POWOnpCnobsnu6vKfbXMOvYv1rtVM4sUEuuBapXQF3vNxXVuK4kJ0S9msJ0ZQo4jsZsNZYpzjwFDzM8cKoFNxOf-AJEeYNGMFkaGQ1hMnZDM0dqEwbFEa8Bz0HUyZWkpsACy8V5HNLhEYgSmZNATlRIPLEPsNJ8_94Kqwx7z9tkripby_89CS71bMJYe6SMmuvuLRn5JfiSB47u7GcDAO8J0-nj7s7U-pNCFGEODxTE_8RRMOBkMyqoJ8SKFNJ875BNPU-T-zsAhqcv6gZdf1838pBnAxkF-1begUlrVmG8nkXI0B89ShmkoJot8H-r378p4D52VYUutfrdQx7wxu92w6egJlulbB_e1XO7zvxgbJ6krodgc2EUyR4iAZkFWzHsiOlYvJ__klLLQCIJEVk8_4VbNC9WSa6q5oo12VgrsHx-hpKMFzndIei2QiwRqY4LxFfYpMbnm5VUnSH_RDWMpKL0h2L5RW346Qhq9KXUL8B8l20hatDqdJid2w_cKijHnpq4crsB6-KyeLwGq2wB9fanDIXmLM0r-NeKMxFo4peS9GLe0Q8sExqVuECspZhyhNj_1-wn-bOu44bjYT7-IaJqgT5nSTyiQvEJ761EpxADAHZx9tsxvsxBjRkw_ajM; path=/; httponly; secure; samesite=strict

{
    Id : 1,
    "Name" :"Test",
    "GroupId" :1,
    "Teacher":null,
    "TeacherId":5
    "Start":null,
    "End":null
}
###
POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=AIzaSyDsD8vONzus0kKJHXIjJeSxrTthW9UG008
# POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=AIzaSyDsD8vONzus0kKJHXIjJeSxrTthW9UG008
Content-Type: application/json
{
  "contents": [{
    "parts":[{"text": "Explain how AI works"}]
    }]
   }
