
@url = https://localhost:44317 
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJUZWFjaGVyMUBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjY5NTQxYWNkLWUzMGYtNDZmYS05OGJkLTFhNTc5Yzk5NjRhMSIsImV4cCI6MTcxNDc2NzMxNiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo0OTAwIiwiYXVkIjoiQVBJIn0.4A0zaFwze3P8Dxc8kZAJDv69U0Xl7MkrSwxAiECso64

# For more info on HTTP files go to https://aka.ms/vs/httpfile
GET {{url}}/api/Global/GetGroup

###
POST  https://localhost:44317/api/Auth/login
Content-Type: application/json

{
  "email": "Teacher1@gmail.com",
  "Password":"Teacher1@123"
}

###
POST {{url}}/odata/Langua/Session/Update?Id=1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{ 
  "Name" : "Test",
  "GroupId" : 1,
  "TeacheriD":1,
  Start : DateTime.Now,
  End : DateTime.Now
}